### PR TITLE
fix: add execution timeout and input validation for X-jq header

### LINKED ISSUE #23: Denial of Service via X-jq header — Add execution timeout and input validation
## Finding

**CVSS:** 6.5 Medium | **Due:** 2026-06-25
**CWE:** CWE-400 (Uncontrolled Resource Consumption), CWE-94 (Code Injection)

## Description

The UI Backend accepts an `X-jq` HTTP header and executes the value as an arbitrary jq expression via the `gojq` library. There is no execution timeout, result count limit, or input length validation.

An authenticated attacker can send expressions like `[range(100000)]` in volume to exhaust CPU/memory, causing 502 Bad Gateway for all users.

**Affected code:** `ParseJQ()` in `utils.go`, called from `mainHandler` (`handlerMain.go`) and `_categoryHandler` (`handlerCategory.go`).

## Required Changes

- [ ] Add execution timeout using `context.WithTimeout` (e.g. 5s) and `query.RunWithContext(ctx, ...)`
- [ ] Cap result iteration at a maximum number of entries (e.g. 10,000)
- [ ] Add configurable maximum input length validation for the `X-jq` header value (reject expressions exceeding the limit)
- [ ] Return generic error messages — do not propagate jq parsing errors to the client

### LINKED ISSUE #24: Dead Code Retained After Feature Removal — Remove ParseJsonPath
## Finding

**Priority:** Low | **Due:** 2026-07-25
**CWE:** CWE-561 (Dead Code)

## Description

The exported function `ParseJsonPath` in `internal/server/utils.go` (lines 57–73) is no longer called anywhere in the codebase. The feature that previously relied on it has been removed, but the function was not cleaned up.

It is a thin wrapper around `k8s.io/client-go/util/jsonpath`. Because it is exported, it is available to any package importing `internal/server`. Its retention also keeps the `jsonpath` import active, maintaining an unnecessary transitive dependency.

## Required Changes

- [ ] Remove the `ParseJsonPath` function from `internal/server/utils.go`
- [ ] Remove the `k8s.io/client-go/util/jsonpath` import (no other function uses it)

### PR DESCRIPTION
**Pull request by n3rdc4ptn**
## Summary

- Adds `context.WithTimeout` to `ParseJQ` using `query.RunWithContext()` to prevent CPU exhaustion from long-running jq expressions
- Caps result iteration at a configurable maximum (default 10,000) to prevent memory exhaustion
- Adds configurable maximum length validation for the `X-jq` header value
- Returns generic error messages to clients instead of leaking internal jq/parsing details
- Removes dead `ParseJsonPath` function and unused `k8s.io/client-go/util/jsonpath` import

### Configuration (env vars)

| Variable | Default | Description |
|---|---|---|
| `JQ_MAX_EXPRESSION_LENGTH` | 500 | Max allowed length of the X-jq header value |
| `JQ_EXECUTION_TIMEOUT_SECONDS` | 5 | Timeout for jq expression execution |
| `JQ_MAX_RESULTS` | 10000 | Max number of result entries from jq iteration |

Closes #23
Closes #24

## Test plan

- [x] `go build ./...` passes
- [x] `go test ./internal/server/...` passes
- [ ] Deploy to staging and verify normal X-jq requests still work
- [ ] Verify that oversized expressions are rejected with 400
- [ ] Verify that long-running expressions (e.g. `[range(100000)]`) are terminated by timeout

### CODE REVIEW

File: cmd/server/main.go [hunk 1]
```diff
@@ -29,11 +30,26 @@ func main() {
 	cachingKube := k8s.NewCachingKube(k8s.HttpKube{}, time.Second*30, time.Minute)
 	downstreamKube := k8s.HttpKube{}
 
-	mux := server.NewMiddleware(cachingKube, downstreamKube)
+	jqConfig := server.JQConfig{
+		MaxExpressionLength: getEnvInt("JQ_MAX_EXPRESSION_LENGTH", 500),
+		ExecutionTimeout:    time.Duration(getEnvInt("JQ_EXECUTION_TIMEOUT_SECONDS", 5)) * time.Second,
```
Comment (ValentinGerlach) [inline cmd/server/main.go]: Alternative: Rename to `JQ_EXECUTION_TIMEOUT` and use [ParseDuration](https://pkg.go.dev/time#ParseDuration).

File: internal/server/handlerCategory.go [hunk 2]
```diff
@@ -110,10 +111,17 @@ func _categoryHandler(s *shared, req *http.Request, res *response) (*response, *
 	result = append(result, []byte("]")[:]...)
 
 	if data.JQ != "" {
-		resultString, err := ParseJQ(result, data.JQ)
+		if s.jqConfig.MaxExpressionLength > 0 && len(data.JQ) > s.jqConfig.MaxExpressionLength {
+			return nil, NewBadRequestError("jq expression exceeds maximum allowed length")
+		}
+
+		ctx, cancel := context.WithTimeout(context.Background(), s.jqConfig.ExecutionTimeout)
```
Comment (ValentinGerlach) [inline internal/server/handlerCategory.go]: I think it would be better to use [Request.Context](https://pkg.go.dev/net/http#Request.Context) here.

```suggestion
		ctx, cancel := context.WithTimeout(req.Context(), s.jqConfig.ExecutionTimeout)
```

File: internal/server/handlerCategory.go [hunk 3]
```diff
@@ -110,10 +111,17 @@ func _categoryHandler(s *shared, req *http.Request, res *response) (*response, *
 	result = append(result, []byte("]")[:]...)
 
 	if data.JQ != "" {
-		resultString, err := ParseJQ(result, data.JQ)
+		if s.jqConfig.MaxExpressionLength > 0 && len(data.JQ) > s.jqConfig.MaxExpressionLength {
```
Comment (ValentinGerlach) [inline internal/server/handlerCategory.go]:
```suggestion
		if len(data.JQ) > s.jqConfig.MaxExpressionLength {
```

Skipping the check if MaxExpressionLength is zero (e.g. because of a bug) is unsafe IMO.

File: internal/server/handlerMain.go [hunk 4]
```diff
@@ -140,7 +130,10 @@ func mainHandler(s *shared, req *http.Request, res *response) (*response, *HttpE
 			return nil, NewInternalServerError("failed to copy response: %v", err)
 		}
 	} else {
-		err := res.buildJqResponse(k8sResp, data)
+		if s.jqConfig.MaxExpressionLength > 0 && len(data.JQ) > s.jqConfig.MaxExpressionLength {
```
Comment (ValentinGerlach) [inline internal/server/handlerMain.go]: Same as above

```suggestion
		if len(data.JQ) > s.jqConfig.MaxExpressionLength {
```

File: internal/server/handlerMain.go [hunk 5]
```diff
@@ -190,15 +183,19 @@ func extractRequestData(r *http.Request) (ExtractedRequestData, error) {
...
 
-func (r *response) buildJqResponse(k8sResp *http.Response, data ExtractedRequestData) error {
+func (r *response) buildJqResponse(k8sResp *http.Response, data ExtractedRequestData, jqConfig JQConfig) error {
 	body, err := io.ReadAll(k8sResp.Body)
 	if err != nil {
 		return errors.Join(errors.New("failed to read api server response"), err)
 	}
 
-	parsedJson, err := ParseJQ(body, data.JQ)
+	ctx, cancel := context.WithTimeout(context.Background(), jqConfig.ExecutionTimeout)
```
Comment (ValentinGerlach) [inline internal/server/handlerMain.go]: Same as above, please use the request's context as the parent context.

**Review by ValentinGerlach — CHANGES_REQUESTED** [review]

**Review by ValentinGerlach — APPROVED** [review]
